### PR TITLE
Use Santa favicon

### PR DESCRIPTION
**Pull request by BurakDev**
Minor improvements.

### CODE REVIEW

**Comment by systeem** [comment]
Yes please, maybe some elves or reindeers wouldn't hurt either.

**Comment by Ekultek** [comment]
Don’t forget the christmas tree

**Comment by Code-Chapter** [comment]
and santa hats

**Comment by MaKiPL** [comment]
+1 = this project will benefit thanks to this great feature!

**Comment by EmeraldSnorlax** [comment]
bro wtf why would you do that you're literally adding swastikas to the code wtf im a sjw this pr offends me!1!1!

**Comment by toriningen** [comment]
🎅 Approved!

LGTM

**Comment by lookaflyingfish** [comment]
🎅 approves.

**Pull request closed without merging**
